# Generated by Django 6.0 on 2026-05-27 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bids', '0002_bid_is_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('sender_phone_snapshot', models.CharField(max_length=20)),
                ('sender_organization_snapshot', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_requests', to='bids.bid')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_contact_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_contact_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['receiver', 'is_read', '-created_at'], name='contacts_co_receive_9f172a_idx'), models.Index(fields=['sender', '-created_at'], name='contacts_co_sender__03bc94_idx'), models.Index(fields=['bid'], name='contacts_co_bid_id_6a06a8_idx')],
                'constraints': [models.UniqueConstraint(fields=('bid', 'sender'), name='unique_contact_request_per_bid_sender')],
            },
        ),
    ]
