# Generated by Django 6.0 on 2026-05-27 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_phoneotp_id_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('legal_address', models.CharField(blank=True, default='', max_length=500)),
                ('inn', models.CharField(blank=True, default='', max_length=12)),
                ('ogrn', models.CharField(blank=True, default='', max_length=15)),
                ('bik', models.CharField(blank=True, default='', max_length=9)),
                ('bank_name', models.CharField(blank=True, default='', max_length=255)),
                ('checking_account', models.CharField(blank=True, default='', max_length=20)),
                ('correspondent_account', models.CharField(blank=True, default='', max_length=20)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('fax', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.CharField(blank=True, default='', max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requisites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
