# Generated by Django 6.0 on 2026-05-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_requisites_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisites',
            name='legal_address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
