# Generated by Django 4.2.20 on 2026-05-27 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_phoneotp_id_alter_user_id'),
        ('users', '0006_alter_requisites_legal_address_to_textfield'),
    ]

    operations = [
    ]
