# Generated by Django 4.2.20 on 2026-05-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20260527_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisites',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
