# Generated by Django 6.0 on 2026-04-22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('title', models.CharField(max_length=255)),
                ('quality', models.CharField(blank=True, default='', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.DecimalField(decimal_places=3, max_digits=12)),
                ('region', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-published_at', '-id'),
            },
        ),
    ]

