# Generated by Django 6.0 on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]

